build:
    environment:
        php:
            version: 5.6.14
            ini:
                'date.timezone': 'Asia/Tokyo'

    tests:
        before:
            -
                environment: { APP_ENV:local, APP_DEBUG:true, APP_KEY:SonarDevZipcode, DB_CONNECTION:sqlite, CACHE_DRIVER:file, QUEUE_DRIVER:sync }
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
