build:
    environment:
        php:
            version: 5.6.14
            ini:
                'date.timezone': 'Asia/Tokyo'

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'clover'
